set_languages("c++latest")
add_requires("safetyhook")

target("cp2077-shared-data")
    set_kind("static")
    if is_mode("ci") then
        set_warnings("all", "error")
    else
        set_warnings("more")
    end
    set_optimize("fastest")
    add_files("src/code/**.cpp")
    add_includedirs("src/include/", { public = true })
    add_includedirs("src/include/Public", { public = true })
    add_headerfiles("src/include/**.hpp")
    add_syslinks("Version", "User32")
    add_defines("WINVER=0x0601", "WIN32_LEAN_AND_MEAN", "NOMINMAX")
    add_packages("safetyhook")
    add_deps("cp2077-shared-data-red::red4ext.sdk", "cp2077-shared-data-red::redlib")

namespace("cp2077-shared-data-red", function()
    target("red4ext.sdk")
        set_default(false)
        set_kind("headeronly")
        set_warnings("none")
        set_group("deps")
        add_headerfiles("deps/red4ext.sdk/vendor/**.h")
        add_headerfiles("deps/red4ext.sdk/include/**.hpp")
        add_includedirs("deps/red4ext.sdk/vendor/")
        add_includedirs("deps/red4ext.sdk/include/", { public = true })

    target("redlib")
        set_default(false)
        set_kind("headeronly")
        set_warnings("none")
        set_group("deps")
        add_defines("NOMINMAX")
        add_headerfiles("deps/redlib/vendor/**.hpp")
        add_headerfiles("deps/redlib/include/**.hpp")
        add_includedirs("deps/redlib/vendor/", { public = true })
        add_includedirs("deps/redlib/include/", { public = true })
end)

add_rules("plugin.vsxmake.autoupdate")
